from maths.basicmaths import *
from maths.electricity import *
from maths.dynamics import *
from maths.radiation import *
from maths.statics import *
from maths.geometry import *
QUESTIONS = [save_tetrahedron_volume_question,save_log_quadratic_question,save_speaker_phase_question,save_young_modulus_question, save_integral_binominal_question,save_ke_force_question,save_cube_side_unknown_samax_question, save_partial_fraction_question, save_rhombus_diagonals_question, save_triangle_sides_unknown_question, save_simplest_proportion_question,save_transformer_pwr_question,save_cylinder_pressure_question, save_no_soln_trigs_question, save_log_rootproduct_question, save_graph_ke_question, save_identical_springs_diff_weights_question, save_a_b_particles_question, save_arithmetic_sum_question, save_collision_question, save_collision_vreversed_distance_question, save_cubic_unknown_derivative_question, save_different_geometric_infinitesum_question, save_equation_curve_unknown_question, save_expand_radical_question, save_fake_slope_fma_question, save_half_life_question, save_obj_upward_obj_released_question, save_power_ke_question, save_proportion_question, save_radicals_question,save_similar_question, save_simple_power_question, save_two_distances_and_times_question, save_wire_wastes_energy_question]
